### ISSUE TITLE
APIClient should renew auth tokens if expired

### ISSUE THREAD

**Issue by mcrute** [mcrute/pydora#11]
When the authentication tokens for a user expire the `APIClient` throws an exception. It should instead try to renew the authentication tokens if needed.

**Comment by jcass77** [comment]
I came across an ```InvalidAuthToken``` exception today, using HEAD of the dict-access branch:

2015-07-19 14:17:08,443 - INFO     Resetting dropped connection: internal-tuner.pandora.com
2015-07-19 14:17:08,865 - WARNING  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-07-19 14:17:12,166 - ERROR    Unhandled exception in Core (urn:uuid:b2c5aed8-4483-48ca-8dcf-6154cbf85616):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/var/lib/git/mopidy/mopidy/listener.py", line 49, in on_event
    getattr(self, event)(**kwargs)
  File "/var/lib/git/mopidy/mopidy/core/actor.py", line 87, in reached_end_of_stream
    self.playback._on_end_of_track()
  File "/var/lib/git/mopidy/mopidy/core/playback.py", line 223, in _on_end_of_track
    self._change_track(next_tl_track)
  File "/var/lib/git/mopidy/mopidy/core/playback.py", line 199, in _change_track
    self._play(on_error_step=on_error_step)
  File "/var/lib/git/mopidy/mopidy/core/playback.py", line 319, in _play
    backend.playback.change_track(tl_track.track).get() and
  File "/usr/local/lib/python2.7/dist-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/var/lib/git/mopidy-pandora/mopidy_pandora/actor.py", line 74, in change_track
    pandora_track = self._next_track(track_uri.station_token)
  File "/var/lib/git/mopidy-pandora/mopidy_pandora/actor.py", line 60, in _next_track
    self.tracks = iter(self.backend.api.get_playlist(station_token))
  File "/var/lib/git/mopidy-pandora/mopidy_pandora/pydora.py", line 39, in get_playlist
    return super(MopidyPandoraAPIClient, self).get_playlist(station_token)
  File "/var/lib/git/pydora/pandora/client.py", line 120, in get_playlist
    includeTrackLength=True))
  File "/var/lib/git/pydora/pandora/client.py", line 93, in __call__
    self._authenticate()
  File "/var/lib/git/pydora/pandora/client.py", line 82, in _authenticate
    returnCapped=True)
  File "/var/lib/git/pydora/pandora/transport.py", line 168, in __call__
    return self._parse_response(result)
  File "/var/lib/git/pydora/pandora/transport.py", line 158, in _parse_response
    raise PandoraException.from_code(result["code"], result["message"])
InvalidAuthToken: Invalid Auth Token
2015-07-19 14:17:12,194 - WARNING  Tried to communicate with dead actor.
2015-07-19 14:17:12,203 - INFO     New MPD connection from [::ffff:127.0.0.1]:53566

I'm not sure why the re-authentication routines would also raise this exception, but it looks to be happening.

**Comment by jcass77** [comment]
This happened after about 90 minutes of continuous playback. Is it not perhaps necessary to also reset the ```start_time``` attribute of the ```APITransport``` instance every time a re-authentication is done?

**Comment by mcrute** [comment]
Yeah I noticed it again too. I'm going to try resetting all transport parameters when partner login happens to see if that fixes it.
