### ISSUE TITLE
Using requests causes pydora connection reset exceptions

### ISSUE THREAD

**Issue by mcrute** [mcrute/pydora#19]
I noticed this three times so far today. It looks like it happens at the end of a playlist.

```
Traceback (most recent call last):
  File "/.../pydora/bin/pydora", line 9, in <module>
    load_entry_point('pydora==1.3.0', 'console_scripts', 'pydora')()
  File "/.../pydora/lib/python3.2/site-packages/pydora/player.py", line 140, in main
    PlayerApp().run()
  File "/.../pydora/lib/python3.2/site-packages/pydora/player.py", line 134, in run
    self.player.play_station(station)
  File "/.../pydora/lib/python3.2/site-packages/pydora/mpg123.py", line 149, in play_station
    for song in iterate_forever(station.get_playlist):
  File "/.../pydora/lib/python3.2/site-packages/pydora/mpg123.py", line 18, in iterate_forever
    output = func(*args, **kwargs)
  File "/.../pydora/lib/python3.2/site-packages/pandora/models/pandora.py", line 24, in get_playlist
    return iter(self._api_client.get_playlist(self.token))
  File "/.../pydora/lib/python3.2/site-packages/pandora/__init__.py", line 299, in get_playlist
    includeTrackLength=True))
  File "/.../pydora/lib/python3.2/site-packages/pandora/__init__.py", line 266, in __call__
    return self.transport(method, **kwargs)
  File "/.../lib/python3.2/site-packages/pandora/__init__.py", line 145, in __call__
    result = self._make_http_request(url, data, params)
  File "/.../pydora/lib/python3.2/site-packages/pandora/__init__.py", line 97, in _make_http_request
    r = self._http.post(url, data=data, params=params)
  File "/.../pydora/lib/python3.2/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/.../pydora/lib/python3.2/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/.../pydora/lib/python3.2/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/.../pydora/lib/python3.2/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by mcrute** [comment]
This seems like it's completely isolated to a bug in python3.2. It might not be worth fixing. However, python3.2 is still the default on the current Ubuntu LTS.

**Comment by mcrute** [comment]
This happened again today with python3.5. Guess this is something that needs fixing after all.

**Comment by mcrute** [comment]
Finally tracked this down today but not able to fix it right now. When creating a session we need to re-mount the HTTPAdapter instances with retries=3 for http:// and https://. That seems to fix the issue.
