### ISSUE TITLE
ParameterMissing exception when requesting next track from iterator

### ISSUE THREAD

**Issue by jcass77** [mcrute/pydora#34]
I came across the following stack trace today:

ERROR    Unhandled exception in PandoraBackend (urn:uuid:3cdfb222-12ef-42bf-bf8f-e3e6978caf66):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/Users/jcass/PycharmProjects/Mopidy/mopidy/mopidy/core/listener.py", line 34, in on_event
    getattr(self, event)(**kwargs)
  File "/Users/jcass/PycharmProjects/Mopidy/mopidy-pandora/mopidy_pandora/backend.py", line 60, in end_of_tracklist_reached
    next_track = self.library.next_track()
  File "/Users/jcass/PycharmProjects/Mopidy/mopidy-pandora/mopidy_pandora/library.py", line 138, in next_track
    pandora_track = self._station_iter.next()
  File "/usr/local/lib/python2.7/site-packages/pydora/utils.py", line 121, in iterate_forever
    yield next(output).prepare_playback()
  File "/usr/local/lib/python2.7/site-packages/pandora/models/pandora.py", line 227, in prepare_playback
    self.register_ad(self.station_id)
  File "/usr/local/lib/python2.7/site-packages/pandora/models/pandora.py", line 224, in register_ad
    self._api_client.register_ad(station_id, self.tracking_tokens)
  File "/usr/local/lib/python2.7/site-packages/pandora/client.py", line 280, in register_ad
    adTrackingTokens=tokens)
  File "/usr/local/lib/python2.7/site-packages/pandora/client.py", line 104, in __call__
    return self.transport(method, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandora/transport.py", line 47, in function
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandora/transport.py", line 234, in __call__
    return self._parse_response(result)
  File "/usr/local/lib/python2.7/site-packages/pandora/transport.py", line 220, in _parse_response
    raise PandoraException.from_code(result["code"], result["message"])
ParameterMissing: Parameter Missing

As best I can tell, there seems to be a parameter missing in the ```register_ad``` call when the track is yielded from the iterator (either the token or the station id)?

**Comment by jcass77** [comment]
I think this field is named incorrectly, should it not be ```stationId```?

https://github.com/mcrute/pydora/blob/f039ae70fd8fcab1a878f5fc072d45ad4cbe44c3/pandora/client.py#L266

**Comment by mcrute** [comment]
Oops, I typo'd that. Fix is released in 1.6.1.
