### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by kcrute** [mcrute/pydora#48]
Pydora stops playing when it runs into special characters. In this instance it's an 'é'. 

```
Traceback (most recent call last):
  File "./pydora/bin/pydora", line 11, in <module>
    sys.exit(main())
  File "/Users/kcrute/pydora/lib/python2.7/site-packages/pydora/player.py", line 199, in main
    PlayerApp().run()
  File "/Users/kcrute/pydora/lib/python2.7/site-packages/pydora/player.py", line 193, in run
    self.player.play_station(station)
  File "/Users/kcrute/pydora/lib/python2.7/site-packages/pydora/mpg123.py", line 97, in play_station
    self.play(song)
  File "/Users/kcrute/pydora/lib/python2.7/site-packages/pydora/mpg123.py", line 62, in play
    self._callbacks.play(song)
  File "/Users/kcrute/pydora/lib/python2.7/site-packages/pydora/player.py", line 97, in play
    print("{} by {}".format(Colors.cyan(song.song_name),
  File "/Users/kcrute/pydora/lib/python2.7/site-packages/pydora/utils.py", line 26, in inner
    return "\033[{}m{}\033[0m".format(code, text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 11: ordinal not in range(128)
```

**Comment by mcrute** [comment]
Ah it looks like the player was accidentally down-casting unicode strings to bytes when doing color formatting, station listing and song printing. I'm testing a fix now which seems to work so this should be released today.
