### ISSUE TITLE
Pydora fails to start

### ISSUE THREAD

**Issue by ksaye** [mcrute/pydora#70]
**What happened**:
pydora fails to start

**What you expected to happen**:
the main menu

**How to reproduce it (as minimally and precisely as possible)**:
1. install pydora 2.0.1
2. run `pydora-config` and put in a known userid and password
3. run `pydora`
4. you should get the error below:

        $ pydora
        Using VLC
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
            (self._dns_host, self.port), self.timeout, **extra_kw)
          File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
            for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
          File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
            for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        socket.gaierror: [Errno -2] Name or service not known
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
            chunked=chunked)
          File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
            self._validate_conn(conn)
          File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
            conn.connect()
          File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
            conn = self._new_conn()
          File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
            self, "Failed to establish a new connection: %s" % e)
        urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb5e04a50>: Failed to establish a new connection: [Errno -2] Name or service not known
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
            timeout=timeout
          File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
            **response_kw)
          File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
            **response_kw)
          File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
            **response_kw)
          File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
            _stacktrace=sys.exc_info()[2])
          File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
            raise MaxRetryError(_pool, url, error or ResponseError(cause))
        urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /services/json/?method=auth.partnerLogin (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5e04a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/bin/pydora", line 10, in <module>
            sys.exit(main())
          File "/usr/local/lib/python3.7/dist-packages/pydora/player.py", line 319, in main
            PlayerApp().run()
          File "/usr/local/lib/python3.7/dist-packages/pydora/player.py", line 292, in run
            self.client = self.get_client()
          File "/usr/local/lib/python3.7/dist-packages/pydora/player.py", line 105, in get_client
            return builder.build()
          File "/usr/local/lib/python3.7/dist-packages/pandora/clientbuilder.py", line 194, in build
            config["USER"]["USERNAME"], config["USER"]["PASSWORD"]
          File "/usr/local/lib/python3.7/dist-packages/pandora/client.py", line 64, in login
            return self._authenticate()
          File "/usr/local/lib/python3.7/dist-packages/pandora/client.py", line 67, in _authenticate
            self._partner_login()
          File "/usr/local/lib/python3.7/dist-packages/pandora/client.py", line 54, in _partner_login
            version=self.transport.API_VERSION,
          File "/usr/local/lib/python3.7/dist-packages/pandora/transport.py", line 51, in function
            return func(*args, **kwargs)
          File "/usr/local/lib/python3.7/dist-packages/pandora/transport.py", line 241, in __call__
            result = self._make_http_request(url, data, params)
          File "/usr/local/lib/python3.7/dist-packages/pandora/transport.py", line 192, in _make_http_request
            result = self._http.post(url, data=data, params=params)
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
            return self.request('POST', url, data=data, json=json, **kwargs)
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
            resp = self.send(prep, **send_kwargs)
          File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
            r = adapter.send(request, **kwargs)
          File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
            raise ConnectionError(e, request=request)
        requests.exceptions.ConnectionError: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /services/json/?method=auth.partnerLogin (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5e04a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Anything else we need to know?**:

**Environment**: Raspbian buster
- Pydora version: 2.0.1
- Python version: 3.7.3
- OS: Linux raspberrypi 5.10.63+ #1457 Tue Sep 28 11:24:51 BST 2021 armv6l GNU/Linux
- Shell (if applicable):
- Others:

**Comment by mcrute** [comment]
Sorry for the slow reply. This does sound like either a mis-configuration or an error on the Pandora side. I don't think they've changed URLs or keys since Pydora has existed so it must have just been an outage on their side.
