### ISSUE TITLE
Error: pandora.errors.InvalidAuthToken: Invalid Auth Token

### ISSUE THREAD

**Issue by ksaye** [mcrute/pydora#74]
**What happened**:
Starting yesterday, I appear to be getting the Invalid Auth Token.

**What you expected to happen**:
No Error message

**How to reproduce it (as minimally and precisely as possible)**:

      ksaye@home:~$ pip3 install pydora
      Collecting pydora
        Downloading pydora-2.2.0-py3-none-any.whl (33 kB)
      Collecting blowfish<1.0,>=0.6.1
        Downloading blowfish-0.6.1.tar.bz2 (27 kB)
      Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.8/dist-packages (from pydora) (2.28.1)
      Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2->pydora) (3.3)
      Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2->pydora) (1.26.10)
      Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2->pydora) (2022.6.15)
      Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2->pydora) (2.1.0)
      Building wheels for collected packages: blowfish
        Building wheel for blowfish (setup.py) ... done
        Created wheel for blowfish: filename=blowfish-0.6.1-py3-none-any.whl size=28133 sha256=6510d404c9d6927a67d570f967a665e56510977198ea5c761def312d48fe8ff5
        Stored in directory: /mnt/disk2/home/ksaye/.cache/pip/wheels/67/5b/0b/b3129ff17820dc866bdf31db2dfdeede2cdf3395aa6627d105
      Successfully built blowfish
      Installing collected packages: blowfish, pydora
      Successfully installed blowfish-0.6.1 pydora-2.2.0
      ksaye@home:~$ pydora-configure
      Welcome to Pydora, let's configure a few things
      Pandora Username: k@saye.org
      Pandora Password:
      ksaye@home:~$ pydora
      Using VLC
      Traceback (most recent call last):
        File "/home/ksaye/.local/bin/pydora", line 8, in <module>
          sys.exit(main())
        File "/home/ksaye/.local/lib/python3.8/site-packages/pydora/player.py", line 310, in main
          PlayerApp().run()
        File "/home/ksaye/.local/lib/python3.8/site-packages/pydora/player.py", line 283, in run
          self.client = self.get_client()
        File "/home/ksaye/.local/lib/python3.8/site-packages/pydora/player.py", line 100, in get_client
          return builder.build()
        File "/home/ksaye/.local/lib/python3.8/site-packages/pandora/clientbuilder.py", line 193, in build
          client.login(
        File "/home/ksaye/.local/lib/python3.8/site-packages/pandora/client.py", line 64, in login
          return self._authenticate()
        File "/home/ksaye/.local/lib/python3.8/site-packages/pandora/client.py", line 70, in _authenticate
          user = self.transport(
        File "/home/ksaye/.local/lib/python3.8/site-packages/pandora/transport.py", line 50, in function
          return func(*args, **kwargs)
        File "/home/ksaye/.local/lib/python3.8/site-packages/pandora/transport.py", line 245, in __call__
          return self._parse_response(result)
        File "/home/ksaye/.local/lib/python3.8/site-packages/pandora/transport.py", line 234, in _parse_response
          raise PandoraException.from_code(result["code"], result["message"])
      pandora.errors.InvalidAuthToken: Invalid Auth Token

**Anything else we need to know?**:

**Environment**:
- Pydora version:  2.2.0
- Python version: 3.8
- OS: Ubuntu
- Shell (if applicable): bash
- Others:

Also reported here: https://github.com/pithos/pithos/issues/701

**Comment by ksaye** [comment]
Ok, so when I tethered my device to my phone, it worked fine -- meaning either my IP is blacklisted or there is a network issue.
